### ISSUE TITLE
Big issue, Developer. This is really getting old. READ COMMENT.

### ISSUE THREAD

**Issue by samlovesgithub** [origin0110/OriginShader#18]
You seriously need to figure out a way to optimize this shader. It's really getting annoying. You are not doing anything to move this shader in the right direction. 

Please make a Discord server so that the users of this shader can discuss with you. If you'd like I'll make the server and invite people to it. Making a discord server is sooo easy. 

I really want this shader to work soon and you clearly aren't doing much to move the progress along. Have a good day.

**Comment by origin0110** [comment]
Sorry... Actually I have a discord server. But I haven't published the invitation link. This is a shader that has just begun development. Most of time I discuss with my Chinese friend in my QQ server. When it is perfect enough, I will publish the invitation link of my discord server

**Comment by origin0110** [comment]
https://discord.gg/reKUV7zGkF
