### ISSUE TITLE
草啊 给你个适配请求 不会用GitHub

### ISSUE THREAD

**Issue by Worldwidebrine** [origin0110/OriginShader#24]
咋发隐藏issue啊
要不你看完这条就直接删了吧
我写了假阴影生成器 求适配：
1. 上午太阳应该固定在(1, 1, 1)方向 下午是(-1, 1, -1)
2. 当 (检测到阴影&&火把亮度等级>0.0) 时 把阴影消除掉
(当然为了自然点可以不完全消除)
(但是必须保证 在亮度等级0.0625的时候 影子不容易被注意到)

Discord的文件链接不知道是不是永久的 要是过期了你来newb shader的Discord下吧
https://cdn.discordapp.com/attachments/880733054304391178/882152715793354812/not_shader13.mcpack
要求：
v1.17.11
主世界
Activate Cheats
GameTest Framework
Holiday Creator Features
最好把Do Daylight Cycle关了
/set time 0和/set time sunset是比较方便切换的有效时间点 不在有效时间段会开始清理阴影方块和光照2方块
代码里一大堆case看你需不需要改

使用方法：

命令me没有/
开了以后再打就是关
开了尽量别乱跑 除非你CPU真的很强 就算强也没用 跑起来可能会被判定成离开主世界

命令hollow
切换空心
当前区块里的阴影方块和光照2方块会被清掉(周围8个区块还是会继续生成的)
开这个可以在当前区块进行小规模的建筑 因为阴影方块不支持像草那样右键一点就被原地覆盖

**Comment by origin0110** [comment]
有联系方式吗

**Comment by Worldwidebrine** [comment]
b站同名 或者QQ？

**Comment by origin0110** [comment]
1090829462你加一下群吧，我并没有写过动态阴影，仅上面的描述也没看懂你想做什么
