### ISSUE TITLE
Lag on Snapdragon 732g

### ISSUE THREAD

**Issue by GhostMobius** [origin0110/OriginShader#42]
I have a SD732g but it lag so much, is my phone cant handle this shaders or something wrong? Thank you.

**Comment by AKPR2007** [comment]
@GhostMobius check [this issue](https://github.com/origin0110/OriginShader/issues/40)

**Comment by GhostMobius** [comment]
Oh even a mid-range can't even run this shaders.

**Comment by AKPR2007** [comment]
@GhostMobius this shader can even run on Snapdragon 600+ but the issue is that it's not in regular development. Don't worry because the optimization will be added very soon

**Comment by AKPR2007** [comment]
@GhostMobius yes it's a problem in the shader

**Comment by GhostMobius** [comment]
Issue has been resolved!
