### ISSUE TITLE
渲染问题

### ISSUE THREAD

**Issue by Rayark-VOEZ** [origin0110/OriginShader#54]
![Screenshot_20220503-184621_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/26689532/166440743-cb875dcd-3a8d-4ab0-adda-8c0b17a3673d.jpg)
设备：oneolus 8
系统：安卓11
版本：1.18.30
问题：无法正确加载光影和材质

**Comment by sheng218** [comment]
Minecraft版本1.18.30添加了渲染龙，无法正确加载任何光影

来源：https://www.minecraft.net/en-us/article/minecraft-1-18-30-bedrock

**Comment by user782** [comment]
正常
1.18.30及以后版本实装渲染龙，所有光影失效
